#ifndef ERRORS_ENUM_H
#define ERRORS_ENUM_H

typedef enum Error {
    SUCCSESS = 0,


    FILE_WRITE_ERROR,
    FILE_NOT_OPEN_ERROR,
    FILE_DELETION_ERROR,

    HIDDEN_FILE_WRITE_ERROR,
    HIDDEN_FILE_NOT_OPEN_ERROR,
    HIDDEN_FILE_DELETION_ERROR,

    HIDER_FORK_ERROR,
    
    HIDER_PIPE_ERROR,

} Error;

#endif